### ISSUE TITLE
Dashes in Github Repository Name Being Converted to Underscores

### ISSUE THREAD

**Issue by niall-byrne** [lob/generate-changelog#61]
I wanted to flag this issue, it might be affecting other people than me.

I have a repository named `panic-fe`, and this yml syntax:

```yaml
- name: Production -- Generate Changelog
        if: env.GIT_DIFF == ''
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
```

The links being rendered look like this for each commit:
https://github.com/niall-byrne/panic-fe/releases/tag/v0.11

My pushy friend made me rename the repository to panic_fe temporarily, so that a github redirect would enable the links to work, but I suspect the author's intention was that they would be rendered differently.
